### ISSUE TITLE
implode() arguments

### ISSUE THREAD

**Issue by Toutouwai** [KeeneState/DebugPerfmon#1]
Thanks for this great module!

The arguments for `implode()` are in the wrong order on [line 187](https://github.com/KeeneState/DebugPerfmon/blob/2b6ea07f787c76e119e741f2af67bad39ea6bc2a/DebugPerfmon.module#L187).

Should be:
```php
print(implode("\n", $output));
```

**Comment by KeeneState** [comment]
Hi Toutouwai, thanks for the report, and good catch. It was residual from when PHP was more permissive about implode argument order. This should be fixed now.
